###
#
# Ansible playbook to perform a daemon upgrade
#
###

- name: Verus Node Upgrade Playbook
  hosts: <hosts>
  become: true
  vars:
    verus_user: verus
    verus_home: "/home/verus"
    verus_executable_dir: "/home/verus/bin"
    git: true
    github_repo: "veruscoin/veruscoin"
    os_keyword: "linux"
    arch_keywords: ["amd64", "x86_64"]
    ext_base_url: "https://symbuild.verus.io"
    verify_with_local_daemon: true

  tasks:
    - name: Determine currently installed version of verusd
      become_user: "{{ verus_user }}"
      shell: |
        set -o pipefail
        "{{ verus_executable_dir }}/verusd" --version 2>/dev/null | head -n1 | cut -f4 -d" "
      args:
        executable: /bin/bash
      register: current_verusd_version_raw
      changed_when: false

    - name: Normalize current version
      set_fact:
        current_verusd_version: "{{ current_verusd_version_raw.stdout }}"

    - name: Fetch latest release metadata from GitHub
      uri:
        url: "https://api.github.com/repos/{{ github_repo }}/releases/latest"
        method: GET
        return_content: yes
        force_basic_auth: yes
      register: git_release_response

    - name: Save the latest release version
      set_fact:
        latest_release: "{{ git_release_response.json.tag_name }}"

    - name: Compare to decide if upgrade needed
      set_fact:
        upgrade_needed: "{{ (latest_release | regex_replace('^v','') | string) is version((current_verusd_version | regex_replace('^v', '') | string), 'gt') }}"

    - name: Show version status
      debug:
        msg: >-
          Current={{ current_verusd_version }}, Latest={{ latest_release }},
          Upgrade needed={{ upgrade_needed }}

    - name: Skip when up to date
      meta: end_host
      when: not upgrade_needed

    - name: Download the latest release
      get_url:
        url: "{{ ext_base_url }}/Verus-CLI-Linux-{{ latest_release }}-x86_64-WithSymbols.tar.gz"
        dest: "/home/verus/"
      become: yes
      become_user: verus

    - name: Proceed with extraction
      shell: 'tar -xzvf /home/verus/Verus-CLI-Linux-{{ latest_release }}-x86_64-WithSymbols.tar.gz && mv verus-cli/verusd bin/verusd; mv verus-cli/verus bin/verus && rm -rf verus-cli && rm Verus-CLI*'
      args:
        chdir:
          /home/verus
      become: yes
      become_user: verus
    #  when: '{{ verify_response.result == true }}'

    - name: Verus stop and restart
      become_user: "{{ verus_user }}"
      block:
      - name: Stop verus daemon if running
        shell: |
          if pgrep -x verusd >/dev/null 2>&1; then
            "{{ verus_executable_dir }}/verus" stop || true
          fi
        args:
          executable: /bin/bash

      - name: Wait until verus daemon is fully stopped
        shell: |
          if pgrep -x verusd >/dev/null 2>&1; then
            echo RUNNING
          else
            echo STOPPED
          fi
        args:
          executable: /bin/bash
        register: verusd_state
        retries: 30
        delay: 2
        until: verusd_state.stdout.strip() == "STOPPED"
        changed_when: false
        failed_when: false  # allow interim "RUNNING" without marking task failed

      - name: Restart verus daemon
        shell: |
          sleep 5 # quick fix in case of latency of process stopping
          cd /home/verus/
          ulimit -Sc unlimited
          "{{ verus_executable_dir }}/verusd" -daemon &>/dev/null
        args:
          executable: /bin/bash

      - name: Wait for verus RPC to be ready
        shell: |
          "{{ verus_executable_dir }}/verus" -rpcwait getinfo >/dev/null 2>&1
        register: verus_rpc_ready
        retries: 30
        delay: 2
        until: verus_rpc_ready.rc == 0
        changed_when: false
        failed_when: false
